### ISSUE TITLE
demo无法运行

### ISSUE THREAD

**Issue by itmanyong** [maitel2020/vite-plugin-uni-twucss#1]
安装依赖后报错无法识别?.语法,这该死的新特性
![image](https://user-images.githubusercontent.com/53500371/170036372-ade3e706-5945-4170-88b3-0f84537fc3c8.png)

**Comment by maitel2020** [comment]
原因是HBuilderX的node版本太低导致的，现在node官方版本是16以上，下载16的（不要18的，太高也会有问题）并安装它，替换掉HBuilderX的node就可以了
![image](https://user-images.githubusercontent.com/38597715/170052163-b2956f0f-9102-441e-8e69-b9763b432989.png)

**Comment by itmanyong** [comment]
感谢！！！
