### ISSUE TITLE
Demo无法正常运行

### ISSUE THREAD

**Issue by lentg** [maitel2020/vite-plugin-uni-twucss#2]
![image](https://user-images.githubusercontent.com/198310/174017192-3a32779a-419a-49c2-b33a-dfd09a9152fd.png)

**Comment by lentg** [comment]
已替换node v16.5.1，无法正常启动，V18的node，也是一样

**Comment by maitel2020** [comment]
看截图，还是没有替换掉。hb实际不止一个地方有node文件，你以为替换了，但实际替换错了地方，麻烦发一下你的路径。

**Comment by lentg** [comment]
![image](https://user-images.githubusercontent.com/198310/174033327-f3a7e0f7-3e3a-4c17-9a5b-7696ee89f275.png)

**Comment by maitel2020** [comment]
看截图你是缺少esbuild-windows-64依赖包，在这个文件夹下安装依赖包
![Uploading IMG_20220616_165858.png…]()

**Comment by maitel2020** [comment]
看截图你是缺少esbuild-windows-64依赖包，在这个文件夹下安装依赖包
![IMG_20220616_165858](https://user-images.githubusercontent.com/38597715/174034845-4866fea8-3a67-4eee-863f-b073df8bd60e.png)
