### ISSUE TITLE
跟mp-html包有冲突

### ISSUE THREAD

**Issue by lentg** [maitel2020/vite-plugin-uni-twucss#4]
插件跟[mp-html](https://ext.dcloud.net.cn/plugin?id=805)包有冲突，H5下没问题，小程序里就不行了，在自带DEMO里，添加mp-html插件后插入下面的代码，就不正常显示了。
`<mp-html content="<b>sssdsdsa</b>" :lazyLoad="true"/>`
![image](https://user-images.githubusercontent.com/198310/174928797-95c9686f-6d31-4aa9-a1ae-bfbfecd5c09d.png)

**Comment by maitel2020** [comment]
请更新1.0.5，已兼容mp-html包。
